### ISSUE TITLE
[SUGGESTIONS]

### ISSUE THREAD

**Issue by Alulululululu** [unsigned-ru/MoshiMoshi#3]
1. second, if a person doesnt use bot for x amount of time, should it remove the person from their friend list then?
2. if the session goes on to long without anyone saying anything at all. (and i mean like when the session started but noone talked at all yet on either side)

(3?) check if theres a limit on how many friends u can add or have in your friend list.

**Comment by MiauwWare** [comment]
@DestinyWolfy , split these up into several issues, there are labels 'bug', 'enchancement' and 'question' Use these to seperate the stuff, so i can mark them as completed one at a time
